### ISSUE TITLE
SConstruct script fails with scons 3.x

### ISSUE THREAD

**Issue by cschreib** [perwin/imfit#5]
... but it is easy to fix! The current SConstruct script sometimes uses the python2 ```print xxx``` syntax instead of the python3-compatible ```print(xxx)```. Just adding the parenthesis allows the script to compile with scons 3.x.

**Comment by perwin** [comment]
Done! (This is simple enough that I'll go ahead and close this issue -- but if you subsequently find it doesn't work, feel free to re-open it!)
