### ISSUE TITLE
how about the unresolved nucleus?

### ISSUE THREAD

**Issue by Xudewang** [perwin/imfit#7]
For galfit, we can use an empirical psf to fit the unresolved nucleus when the sersic function may be not very useful. I am confused about how to use just a psf to fit the unresolved nucleus in the limfit. Thanks very much!

**Comment by perwin** [comment]
Pretty much the same way you'd do it in GALFIT. In Imfit, you use the PointSource image function, which has one parameter (the total flux of the point source). You have to remember to tell imfit about the PSF image (via --psf=<psf-image-name>), of course!

FUNCTION PointSource
I_tot   <initial-value>   [possible lower & upper limits]

**Comment by Xudewang** [comment]
Thanks a lot! Before I just read the quick start and part of your paper (2015) without seeing the PointSource function. I will read the documentation carefully. Thanks!

**Comment by perwin** [comment]
The problem is that the PointSource function was added after the paper was published, so it's not mentioned there ;-)... The PDF documention file (imfit_howto.pdf) is the most complete and up-to-date source, though I'm working on making the online documentation more complete as well.

**Comment by Xudewang** [comment]
The current online documentation is fantastic! It is really friendly to beginner. Look forward to a more complete one!

**Comment by perwin** [comment]
Thanks, glad to hear it's useful! (And feel free to offer any suggestions or questions you might have about it.)
