### ISSUE TITLE
The problem of multi-component fitting

### ISSUE THREAD

**Issue by PaulLiu666** [perwin/imfit#9]
![image](https://github.com/perwin/imfit/assets/94830897/143b8318-ee41-4811-a2d8-77fa46b74cc3)
I fitted an elliptical galaxy using three series models and output a comprehensive best fit model. 
I calculated the radial brightness distribution of the original data and the best fit model, with label distributions of "data" and "ALL". 
Then I drew the radial distribution of the three components based on the output parameters, but found that one component was very prominent. 
I want to know how these three components are combined to obtain the best fitting model? 
Thank you for watching, and I hope you can help me.

**Comment by perwin** [comment]
Hi Paul,

For each component, Imfit constructs an image using the component parameters, then adds all the images together -- and finally convolves the result with the PSF, if any. (The latter is mathematically equivalent to doing PSF convolution on the individual-component images and then adding them together.)

If you want to see what the individual model components look like as images, you can run `makeimage` with the `--output-functions` option. Be sure to include the PSF image if you were using that in your fit; it will be used to convolve each model-component image appropriately.

Without any more details of your fit, I would guess that either

1. The *convolved* profile of sersic3 (assuming you used PSF convolution in the fit) will look different from what you plotted;
2. Something is wrong in your generation of the sersic3 profile.

Did you include PSF convolution in your fit? (And: what is the pixel scale?)

**Comment by PaulLiu666** [comment]
Thank you very much! The pixel scale is 0.05''/pixel.
I did use PSF when generating the best fit model.
But I did not consider the convolution of PSF when generating individual components using the output parameters.
I will check PSF convolution. 
Thank you for your answer. This is very important to me!

**Comment by perwin** [comment]
Something I sometimes do is generate the convolved, individual-component images (`makeimage --output-functions`), then plot major-axis cuts through them, as well as major-axis cuts through the combined model image and the data image. Or, if your data profile happens to come from say ellipse-fitting, generate ellipse-fit profiles for the model images using the same x0,y0,ellipticity,PA parameters. This is perhaps easier and probably better than trying to convolve a 1D Sersic profile with a PSF-based 1D kernel.
